import type { AppUser, EmployeeStatus, RequestItem, TimeLog } from './types'

export const mockUsers: AppUser[] = [
  {
    id: 'emp-1024',
    role: 'employee',
    name: 'Tai Manguiat',
    initials: 'TM',
    employeeId: 'EMP-1024',
    department: 'Operations',
    position: 'DTR Coordinator',
    email: 'tai.manguiat@company.com',
    mobile: '+63 917 555 0142',
    shiftSchedule: '8:00 AM - 5:00 PM',
    manager: 'A. Rivera',
    location: 'Main Lobby Hub',
    password: 'employee123',
  },
  {
    id: 'adm-0001',
    role: 'admin',
    name: 'Andrea Rivera',
    initials: 'AR',
    employeeId: 'ADM-0001',
    department: 'Operations',
    position: 'DTR Administrator',
    email: 'andrea.rivera@company.com',
    mobile: '+63 917 555 0101',
    shiftSchedule: '8:00 AM - 5:00 PM',
    manager: 'HR Director',
    location: 'Operations Command Desk',
    password: 'admin123',
  },
]

export const employeeTimeLogs: TimeLog[] = [
  {
    id: 'may28',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'THU',
    dateNumber: '28',
    monthLabel: 'MAY',
    dateTitle: 'Thu, May 28',
    summary: '8:02 AM in • 12:01 PM break • 1:03 PM resume • 5:05 PM out',
    duration: '8h 03m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may27',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'WED',
    dateNumber: '27',
    monthLabel: 'MAY',
    dateTitle: 'Wed, May 27',
    summary: '7:57 AM in • 12:00 PM break • 1:01 PM resume • 5:02 PM out',
    duration: '8h 04m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may26',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'TUE',
    dateNumber: '26',
    monthLabel: 'MAY',
    dateTitle: 'Tue, May 26',
    summary: '8:06 AM in • 12:02 PM break • 1:02 PM resume • 5:11 PM out',
    duration: '8h 01m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may25',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'MON',
    dateNumber: '25',
    monthLabel: 'MAY',
    dateTitle: 'Mon, May 25',
    summary: '8:00 AM in • 12:00 PM break • 1:00 PM resume • 5:00 PM out',
    duration: '8h 00m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may24',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SUN',
    dateNumber: '24',
    monthLabel: 'MAY',
    dateTitle: 'Sun, May 24',
    summary: '8:10 AM in • 12:05 PM break • 1:06 PM resume • 5:22 PM out',
    duration: '8h 11m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may23',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SAT',
    dateNumber: '23',
    monthLabel: 'MAY',
    dateTitle: 'Sat, May 23',
    summary: '7:58 AM in • 12:00 PM break • 1:01 PM resume • 5:04 PM out',
    duration: '8h 05m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may22',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'FRI',
    dateNumber: '22',
    monthLabel: 'MAY',
    dateTitle: 'Fri, May 22',
    summary: '8:04 AM in • 12:01 PM break • 1:03 PM resume • 5:06 PM out',
    duration: '7h 58m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may21',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'THU',
    dateNumber: '21',
    monthLabel: 'MAY',
    dateTitle: 'Thu, May 21',
    summary: '8:01 AM in • 12:00 PM break • 1:02 PM resume • 5:07 PM out',
    duration: '8h 04m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may20',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'WED',
    dateNumber: '20',
    monthLabel: 'MAY',
    dateTitle: 'Wed, May 20',
    summary: '8:07 AM in • 12:04 PM break • 1:03 PM resume • 5:15 PM out',
    duration: '8h 01m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may19',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'TUE',
    dateNumber: '19',
    monthLabel: 'MAY',
    dateTitle: 'Tue, May 19',
    summary: '7:59 AM in • 12:00 PM break • 1:01 PM resume • 5:02 PM out',
    duration: '8h 02m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may18',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'MON',
    dateNumber: '18',
    monthLabel: 'MAY',
    dateTitle: 'Mon, May 18',
    summary: '8:03 AM in • 12:02 PM break • 1:04 PM resume • 5:06 PM out',
    duration: '7h 57m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may17',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SUN',
    dateNumber: '17',
    monthLabel: 'MAY',
    dateTitle: 'Sun, May 17',
    summary: '8:08 AM in • 12:01 PM break • 1:03 PM resume • 5:16 PM out',
    duration: '8h 06m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may16',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SAT',
    dateNumber: '16',
    monthLabel: 'MAY',
    dateTitle: 'Sat, May 16',
    summary: '8:00 AM in • 12:00 PM break • 1:02 PM resume • 5:03 PM out',
    duration: '8h 01m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may15',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'FRI',
    dateNumber: '15',
    monthLabel: 'MAY',
    dateTitle: 'Fri, May 15',
    summary: '8:05 AM in • 12:03 PM break • 1:02 PM resume • 5:09 PM out',
    duration: '7h 59m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may14',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'THU',
    dateNumber: '14',
    monthLabel: 'MAY',
    dateTitle: 'Thu, May 14',
    summary: '7:56 AM in • 12:00 PM break • 1:00 PM resume • 5:01 PM out',
    duration: '8h 05m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may13',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'WED',
    dateNumber: '13',
    monthLabel: 'MAY',
    dateTitle: 'Wed, May 13',
    summary: '8:09 AM in • 12:02 PM break • 1:04 PM resume • 5:18 PM out',
    duration: '8h 03m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may12',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'TUE',
    dateNumber: '12',
    monthLabel: 'MAY',
    dateTitle: 'Tue, May 12',
    summary: '8:02 AM in • 12:01 PM break • 1:02 PM resume • 5:04 PM out',
    duration: '7h 59m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may11',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'MON',
    dateNumber: '11',
    monthLabel: 'MAY',
    dateTitle: 'Mon, May 11',
    summary: '7:58 AM in • 12:00 PM break • 1:01 PM resume • 5:03 PM out',
    duration: '8h 04m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may10',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SUN',
    dateNumber: '10',
    monthLabel: 'MAY',
    dateTitle: 'Sun, May 10',
    summary: '8:06 AM in • 12:02 PM break • 1:03 PM resume • 5:14 PM out',
    duration: '8h 03m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may09',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SAT',
    dateNumber: '09',
    monthLabel: 'MAY',
    dateTitle: 'Sat, May 9',
    summary: '8:01 AM in • 12:00 PM break • 1:01 PM resume • 5:05 PM out',
    duration: '8h 03m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may08',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'FRI',
    dateNumber: '08',
    monthLabel: 'MAY',
    dateTitle: 'Fri, May 8',
    summary: '8:00 AM in • 12:01 PM break • 1:02 PM resume • 5:01 PM out',
    duration: '7h 58m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may07',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'THU',
    dateNumber: '07',
    monthLabel: 'MAY',
    dateTitle: 'Thu, May 7',
    summary: '8:08 AM in • 12:03 PM break • 1:04 PM resume • 5:17 PM out',
    duration: '8h 02m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may06',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'WED',
    dateNumber: '06',
    monthLabel: 'MAY',
    dateTitle: 'Wed, May 6',
    summary: '7:57 AM in • 12:00 PM break • 1:01 PM resume • 5:02 PM out',
    duration: '8h 04m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may05',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'TUE',
    dateNumber: '05',
    monthLabel: 'MAY',
    dateTitle: 'Tue, May 5',
    summary: '8:01 AM in • 12:00 PM break • 1:02 PM resume • 5:06 PM out',
    duration: '8h 03m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'may04',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'MON',
    dateNumber: '04',
    monthLabel: 'MAY',
    dateTitle: 'Mon, May 4',
    summary: '7:56 AM in • 12:01 PM break • 1:00 PM resume • 5:01 PM out',
    duration: '8h 04m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'may02',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'SAT',
    dateNumber: '02',
    monthLabel: 'MAY',
    dateTitle: 'Sat, May 2',
    summary: '8:09 AM in • 12:02 PM break • 1:03 PM resume • 5:18 PM out',
    duration: '8h 06m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'may01',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'FRI',
    dateNumber: '01',
    monthLabel: 'MAY',
    dateTitle: 'Fri, May 1',
    summary: '8:00 AM in • 12:00 PM break • 1:01 PM resume • 5:00 PM out',
    duration: '7h 59m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'apr28',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'TUE',
    dateNumber: '28',
    monthLabel: 'APR',
    dateTitle: 'Tue, Apr 28',
    summary: '8:03 AM in • 12:01 PM break • 1:04 PM resume • 5:04 PM out',
    duration: '8h 01m',
    accent: '#2563eb',
    accentSoft: '#eaf2ff',
  },
  {
    id: 'apr27',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'MON',
    dateNumber: '27',
    monthLabel: 'APR',
    dateTitle: 'Mon, Apr 27',
    summary: '7:58 AM in • 12:00 PM break • 1:02 PM resume • 5:02 PM out',
    duration: '8h 12m',
    accent: '#0f766e',
    accentSoft: '#eaf8f2',
  },
  {
    id: 'apr25',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    dayLabel: 'FRI',
    dateNumber: '25',
    monthLabel: 'APR',
    dateTitle: 'Fri, Apr 25',
    summary: '8:11 AM in • 12:03 PM break • 1:00 PM resume • 5:08 PM out',
    duration: '7h 54m',
    accent: '#f97316',
    accentSoft: '#fff3e6',
  },
  {
    id: 'apr24-ar',
    employeeName: 'Andrea Rivera',
    department: 'Operations',
    dayLabel: 'THU',
    dateNumber: '24',
    monthLabel: 'APR',
    dateTitle: 'Thu, Apr 24',
    summary: '8:00 AM in • 12:00 PM break • 1:03 PM resume • 5:00 PM out',
    duration: '7h 57m',
    accent: '#64748b',
    accentSoft: '#eef3f8',
  },
  {
    id: 'apr23-js',
    employeeName: 'J. Santos',
    department: 'Finance',
    dayLabel: 'WED',
    dateNumber: '23',
    monthLabel: 'APR',
    dateTitle: 'Wed, Apr 23',
    summary: '8:06 AM in • 12:02 PM break • 1:01 PM resume • 5:06 PM out',
    duration: '8h 01m',
    accent: '#64748b',
    accentSoft: '#eef3f8',
  },
]

export const employeeRequestItems: RequestItem[] = [
  {
    id: 'overtime-approval',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    title: 'Overtime approval',
    requestType: 'Overtime',
    status: 'Pending',
    statusColor: '#d97706',
    statusSoft: '#fff0d9',
    summary: 'Apr 25 • 2h 00m • Waiting for manager review',
    submittedAt: 'April 25, 2026 • 6:14 PM',
    effectiveLabel: 'April 25, 2026 • 2h 00m overtime',
    lastUpdated: 'April 25, 2026 • 6:26 PM',
    reviewer: 'A. Rivera',
    reviewerComment: 'Need confirmation that payroll close support extended beyond the scheduled shift.',
    sourceProof: 'Biometric overtime log and payroll closeout checklist',
    accent: '#f59e0b',
    accentSoft: '#fff7e8',
    details: [
      { label: 'Request ID', value: 'OT-2026-0425' },
      { label: 'Employee', value: 'Tai Manguiat' },
      { label: 'Date filed', value: 'April 25, 2026 • 6:14 PM' },
      { label: 'Effective date', value: 'April 25, 2026' },
      { label: 'Requested hours', value: '2h 00m' },
      { label: 'Coverage', value: 'No coverage needed' },
      { label: 'Proof / source', value: 'Biometric overtime log and payroll closeout checklist' },
      { label: 'Reason', value: 'Month-end reconciliation and payroll review support.', emphasis: true },
      { label: 'Approver', value: 'A. Rivera' },
    ],
    timeline: [
      { label: 'Submitted', value: 'April 25, 2026 • 6:14 PM', note: 'Employee submitted overtime request after shift close.' },
      { label: 'Manager review', value: 'April 25, 2026 • 6:26 PM', note: 'Marked pending while validating task completion window.' },
      { label: 'Current status', value: 'Pending', note: 'Awaiting final approval from operations admin.' },
    ],
  },
  {
    id: 'time-correction',
    employeeName: 'Tai Manguiat',
    department: 'Operations',
    title: 'Time correction',
    requestType: 'Correction',
    status: 'Approved',
    statusColor: '#17835f',
    statusSoft: '#ddf6e9',
    summary: 'Apr 19 • Missing clock-out corrected to 5:03 PM',
    submittedAt: 'April 19, 2026 • 5:31 PM',
    effectiveLabel: 'April 19, 2026 • Missing clock-out',
    lastUpdated: 'April 19, 2026 • 6:02 PM',
    reviewer: 'A. Rivera',
    reviewerComment: 'Approved after matching the correction against the biometric terminal export.',
    sourceProof: 'Biometric log export and supervisor confirmation',
    accent: '#10b981',
    accentSoft: '#eef8f2',
    details: [
      { label: 'Request ID', value: 'TC-2026-0419' },
      { label: 'Employee', value: 'Tai Manguiat' },
      { label: 'Date filed', value: 'April 19, 2026 • 5:31 PM' },
      { label: 'Affected log date', value: 'April 19, 2026' },
      { label: 'Correction', value: 'Missing clock-out', emphasis: true },
      { label: 'Expected time in/out', value: '7:58 AM / 5:03 PM' },
      { label: 'Break adjustment', value: 'None' },
      { label: 'Proof / source', value: 'Biometric log export and supervisor confirmation' },
      { label: 'Adjusted time', value: '5:03 PM' },
      { label: 'Approved by', value: 'A. Rivera' },
    ],
    timeline: [
      { label: 'Submitted', value: 'April 19, 2026 • 5:31 PM', note: 'Employee filed a missing clock-out correction.' },
      { label: 'Validated', value: 'April 19, 2026 • 5:48 PM', note: 'Biometric export matched expected clock-out time.' },
      { label: 'Approved', value: 'April 19, 2026 • 6:02 PM', note: 'Attendance record updated for payroll processing.' },
    ],
  },
  {
    id: 'leave-ar',
    employeeName: 'M. Cruz',
    department: 'Field Support',
    title: 'Leave request',
    requestType: 'Leave',
    status: 'Pending',
    statusColor: '#d97706',
    statusSoft: '#fff0d9',
    summary: 'Apr 30 • Emergency leave • Awaiting final review',
    submittedAt: 'April 29, 2026 • 4:22 PM',
    effectiveLabel: 'April 30, 2026 • Full day',
    lastUpdated: 'April 29, 2026 • 4:40 PM',
    reviewer: 'Andrea Rivera',
    reviewerComment: 'Coverage has been assigned. Final confirmation pending before the next dispatch schedule is published.',
    sourceProof: 'Medical appointment notice',
    accent: '#f59e0b',
    accentSoft: '#fff7e8',
    details: [
      { label: 'Request ID', value: 'LV-2026-0430' },
      { label: 'Employee', value: 'M. Cruz' },
      { label: 'Date filed', value: 'April 29, 2026 • 4:22 PM' },
      { label: 'Leave type', value: 'Emergency leave' },
      { label: 'Date coverage', value: 'April 30, 2026 • Full day' },
      { label: 'Coverage', value: 'Supervisor-managed coverage' },
      { label: 'Attachment', value: 'Medical appointment notice' },
      { label: 'Reason', value: 'Family medical appointment requiring full-day absence.', emphasis: true },
      { label: 'Approver', value: 'Andrea Rivera' },
    ],
    timeline: [
      { label: 'Submitted', value: 'April 29, 2026 • 4:22 PM', note: 'Employee filed an emergency leave request.' },
      { label: 'Coverage assigned', value: 'April 29, 2026 • 4:31 PM', note: 'Supervisor-managed coverage marked in the schedule.' },
      { label: 'Current status', value: 'Pending', note: 'Awaiting final review before dispatch plan release.' },
    ],
  },
]

export const employeeStatuses: EmployeeStatus[] = [
  {
    id: 'emp-1024',
    name: 'Tai Manguiat',
    department: 'Operations',
    status: 'Clocked In',
    statusColor: '#17835f',
    statusSoft: '#ecf9f1',
    schedule: '8:00 AM - 5:00 PM',
    lastActivity: 'Clocked in at 8:01 AM',
  },
  {
    id: 'emp-1092',
    name: 'Andrea Rivera',
    department: 'Operations',
    status: 'On Break',
    statusColor: '#d97706',
    statusSoft: '#fff4e6',
    schedule: '8:00 AM - 5:00 PM',
    lastActivity: 'Break started at 12:06 PM',
  },
  {
    id: 'emp-1148',
    name: 'J. Santos',
    department: 'Finance',
    status: 'Late',
    statusColor: '#dc2626',
    statusSoft: '#feecec',
    schedule: '8:00 AM - 5:00 PM',
    lastActivity: 'Clocked in at 8:17 AM',
  },
  {
    id: 'emp-1217',
    name: 'M. Cruz',
    department: 'Field Support',
    status: 'Clocked Out',
    statusColor: '#64748b',
    statusSoft: '#eef3f8',
    schedule: '7:00 AM - 4:00 PM',
    lastActivity: 'Shift closed at 4:03 PM',
  },
]
